export const initialConstructionItems = [
    {
        section: "1.1",
        item_no: 1.1,
        sub_item: "",
        item_title: "การปักเสา, เสาตอม่อ (ความลึก, แนวเสา, หน้าเสา)",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
    },
    {
        section: "1.2",
        item_no: 1.2,
        sub_item: "",
        item_title: "การติดตั้งคอน ลูกถ้วย และประกอบบอนด์ไวร์",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
    },
{
        section: "1.3",
        item_no: 1.3,
        sub_item: "",
        item_title: "การติดตั้งเหล็กรับสายล่อฟ้า (เหล็กฉาก , เหล็กรูปรางน้ํา)",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.4",
        item_no: 1.4,
        sub_item: "",
        item_title: "การฝังสมอบก และประกอบยึดโยงระบบจําหน่าย",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.5",
        item_no: 1.5,
        sub_item: "",
        item_title: "การฝังสมอบก และประกอบยึดโยงสายล่อฟ้า",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.6",
        item_no: 1.6,
        sub_item: "",
        item_title: "การพาดสายไฟ ระยะหย่อนยาน",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.7",
        item_no: 1.7,
        sub_item: "",
        item_title: "การพาดสายล่อฟ้า ระยะหย่อนยาน",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.8",
        item_no: 1.8,
        sub_item: "1",
        item_title: "ข้ามถนน > 6.1 ม., ข้ามทางหลวง 22 kV > 7.5 ม.",
        other: "",
        result: "-",
        detail: "ข้ามถนน > 6.1 ม., ข้ามทางหลวง 22 kV > 7.5 ม.",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.8",
        item_no: 1.8,
        sub_item: "2",
        item_title: "ข้ามทางรถไฟ > 9 ม.",
        other: "",
        result: "-",
        detail: " ข้ามทางรถไฟ > 9 ม.",
        note: "",
        value1: "",
        value2: "",
        type: ""
},{
        section: "1.8",
        item_no: 1.8,
        sub_item: "3",
        item_title: "ระยะห่างสายด้านข้างกับสิ่งก่อสร้างต่างๆ",
        other: "",
        result: "-",
        detail: "ระยะห่างสายด้านข้างกับสิ่งก่อสร้างต่างๆ",
        note: "",
        value1: "",
        value2: "",
        type: ""
},{
        section: "1.8",
        item_no: 1.8,
        sub_item: "4",
        item_title: "ระยะห่างระบบจําหน่ายแรงสูง กับสายส่ง",
        other: "",
        result: "-",
        detail: "ระยะห่างระบบจําหน่ายแรงสูง กับสายส่ง",
        note: "",
        value1: "",
        value2: "",
        type: ""
},{
        section: "1.8",
        item_no: 1.8,
        sub_item: "5",
        item_title: "ระยะห่างระบบจําหน่ายแรงสูง กับแรงต่ํา",
        other: "",
        result: "-",
        detail: "ระยะห่างระบบจําหน่ายแรงสูง กับแรงต่ํา",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.9",
        item_no: 1.9,
        sub_item: "",
        item_title: "การพันและผูกลูกถ้วย",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.10",
        item_no: 1.10,
        sub_item: "",
        item_title: "การต่อสาย พันเทป(สายหุ้มฉนวน)",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.11",
        item_no: 1.11,
        sub_item: "",
        item_title: "การเชื่อมสาย, สายแยก พันเทป(สายหุ้มฉนวน)",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.12",
        item_no: 1.12,
        sub_item: "",
        item_title: "การเข้าปลายสาย",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.13",
        item_no: 1.13,
        sub_item: "",
        item_title: "การตัดต้นไม้",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.14",
        item_no: 1.14,
        sub_item: "",
        item_title: "การทาสีเสา",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.15",
        item_no: 1.15,
        sub_item: "",
        item_title: "การพ่นสี หมายเลขเสา",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.16",
        item_no: 1.16,
        sub_item: "",
        item_title: "การยึดโยง(storm guy, line guy, fix guy, etc.)",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.17",
        item_no: 1.17,
        sub_item: "",
        item_title: "การต่อลงดิน",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",   // ค่าความต้านทานดินต่อจุด (โอห์ม)
        value2: "",   // ระบบ (โอห์ม)
        type: ""
},
{
        section: "1.18",
        item_no: 1.18,
        sub_item: "",
        item_title: "การติดตั้งกับดักเสิร์จแรงสูง",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
{
        section: "1.19",
        item_no: 1.19,
        sub_item: "",
        item_title: "อื่นๆ",
        other: "",
        result: "-",
        detail: "",
        note: "",
        value1: "",
        value2: "",
        type: ""
},
        // Section 2: ระบบจําหน่ายแรงต่ํา
        {
                section: "2.1",
                item_no: 2.1,
                sub_item: "",
                item_title: "การปักเสา, เสาตอม่อ (ความลึก, แนวเสา, หน้าเสา)",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.2",
                item_no: 2.2,
                sub_item: "",
                item_title: "การติดตั้งคอน แร็ค",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.3",
                item_no: 2.3,
                sub_item: "",
                item_title: "การฝังสมอบก และประกอบยึดโยง",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.4",
                item_no: 2.4,
                sub_item: "",
                item_title: "การพาดสายไฟ ระยะหย่อนยาน",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.5",
                item_no: 2.5,
                sub_item: "1",
                item_title: "ระยะห่าง, ความสูงของสายไฟ",
                other: "",
                result: "-",
                detail: "ข้ามถนน > 5.5 ม., ข้ามทางหลวง > 6.0 ม.",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.5",
                item_no: 2.5,
                sub_item: "2",
                item_title: "ระยะห่าง, ความสูงของสายไฟ",
                other: "",
                result: "-",
                detail: "ข้ามทางรถไฟ > 7 ม.",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.6",
                item_no: 2.6,
                sub_item: "",
                item_title: "การผูกสายไฟกับลูกรอกแรงต่ํา",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.7",
                item_no: 2.7,
                sub_item: "",
                item_title: "การต่อสาย พันเทป การเข้าปลายสายข้างเดียว",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.8",
                item_no: 2.8,
                sub_item: "",
                item_title: "การเชื่อมสาย, สายแยก พันเทป การเข้าปลายสายข้างเดียว",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.9",
                item_no: 2.9,
                sub_item: "",
                item_title: "การเข้าปลายสาย พันเทป การเข้าปลายสายสองข้าง",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.10",
                item_no: 2.10,
                sub_item: "",
                item_title: "การติดตั้งกับดักเสิร์จแรงต่ํา พันเทป",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.11",
                item_no: 2.11,
                sub_item: "",
                item_title: "การทาสีเสา",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.12",
                item_no: 2.12,
                sub_item: "",
                item_title: "การพ่นสี หมายเลขเสา",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.13",
                item_no: 2.13,
                sub_item: "",
                item_title: "การยึดโยง(storm guy, line guy, fix guy)",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.14",
                item_no: 2.14,
                sub_item: "",
                item_title: "การต่อลงดิน",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "2.15",
                item_no: 2.15,
                sub_item: "",
                item_title: "ค่าความต้านทานดินรวม",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",   // ค่าความต้านทานดินรวม (โอห์ม)
                value2: "",
                type: ""
        },
        {
                section: "2.16",
                item_no: 2.16,
                sub_item: "",
                item_title: "อื่นๆ",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        // Section 3: การติดตั้งหม้อแปลง
         {
                section: "3",
                item_no: 3,
                sub_item: "",
                item_title: " การติดตั้งหม้อแปลง ",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",//tr
                value2: "",//kVA
                type: "" // แขวนเสา,นั่งร้าน 
        },
        {
                section: "3.1",
                item_no: 3.1,
                sub_item: "",
                item_title: "การติดตั้งหม้อแปลง (ระยะความสูง, ทิศทาง)",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.2",
                item_no: 3.2,
                sub_item: "",
                item_title: "การติดตั้งคอน ลูกถ้วย และประกอบบอนด์ไวร์",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.3",
                item_no: 3.3,
                sub_item: "",
                item_title: "การพาดสายแรงสูงเข้าหม้อแปลง และลําดับเฟส",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.4",
                item_no: 3.4,
                sub_item: "",
                item_title: "การผูกสายไฟกับลูกถ้วย",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.5",
                item_no: 3.5,
                sub_item: "",
                item_title: "การติดตั้งกับดักเสิร์จแรงสูง, หางปลา",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.6",
                item_no: 3.6,
                sub_item: "",
                item_title: "การติดตั้งดร็อปเอาต์, พินเทอร์มินอล และฟิวส์ลิงก์",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.7",
                item_no: 3.7,
                sub_item: "",
                item_title: "การติดตั้งคอนสปัน 3,200 มม. ระยะความสูง",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.8",
                item_no: 3.8,
                sub_item: "",
                item_title: "การเข้าสายที่บุชชิ่งหม้อแปลง, หางปลา, ฉนวนครอบบุชชิ่ง",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.9",
                item_no: 3.9,
                sub_item: "",
                item_title: "การติดตั้งสายแรงต่ํา และลําดับเฟส",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.10",
                item_no: 3.10,
                sub_item: "",
                item_title: "การติดตั้งกับดักเสิร์จแรงต่ํา พันเทป",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.11",
                item_no: 3.11,
                sub_item: "",
                item_title: "การติดตั้งคอนสําหรับ LT, LT สวิตช์ และ ฟิวส์แรงต่ํา",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.12",
                item_no: 3.12,
                sub_item: "",
                item_title: "การติดตั้งที่จับขอบถัง, เหล็กแขวน ท่อร้อยสายแรงต่ํา",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.13",
                item_no: 3.13,
                sub_item: "",
                item_title: "เทคอนกรีตที่คาน , โคนเสา",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.14",
                item_no: 3.14,
                sub_item: "1",
                item_title: "การต่อลงดิน",
                other: "",
                result: "-",
                detail: "ตัวถังหม้อแปลง",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.14",
                item_no: 3.14,
                sub_item: "2",
                item_title: "การต่อลงดิน",
                other: "",
                result: "-",
                detail: "สายกราวด์ด้านแรงสูง",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.14",
                item_no: 3.14,
                sub_item: "3",
                item_title: "การต่อลงดิน",
                other: "",
                result: "-",
                detail: "สายกราวด์ด้านแรงต่ํา",
                note: "",
                value1: "",
                value2: "",
                type: ""
        },
        {
                section: "3.15",
                item_no: 3.15,
                sub_item: "",
                item_title: "ค่าความต้านทานดินต่อจุด",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",   // ค่าความต้านทานดินต่อจุด (โอห์ม)
                value2: "",   // ระบบ (โอห์ม)
                type: ""
        },
        {
                section: "3.16",
                item_no: 3.16,
                sub_item: "",
                item_title: "อื่นๆ",
                other: "",
                result: "-",
                detail: "",
                note: "",
                value1: "",
                value2: "",
                type: ""
        }
];
export default initialConstructionItems;