const initialEvHvChargerForm = {
  // General Information
  general: {
    customerName: "",
    customerNumber: "",
    address: "",
    inspectionDate: "",
    inspector: "",
    area: ""
  },

  // Documents
  documents: {
    electricalDocument: null // "has" or "none"
  },

  // HV System
  hvSystem: {
    mode: null, // "above" (เหนือดิน) หรือ "under" (ใต้ดิน)
    // Dynamic items เช่น "3.1_1", "3.1_2", ... หรือ "3.2_1", ... ตาม prefix
    "3.1_1": { result: null, text: "", detail: "" },
    "3.1_2": { result: null, text: "", detail: "" },
    "3.1_3": { result: null, detail: "" },
    "3.1_4": { result: null, detail: "" },
    "3.1_5": { result: null, detail: "" },
    "3.1_6": { result: null, detail: "" },
    "3.1_7": { result: null, detail: "" },
    "3.1_8": { result: null, detail: "" },
    "3.1_9": { result: null, detail: "" },
    "3.1_10": { result: null, detail: "" },
    "3.1_11": { result: null, detail: "" },

    "3.2_1": { result: null, text: "", detail: "" },
    "3.2_2": { result: null, text: "", detail: "" },
    "3.2_3": { result: null, detail: "" },
    "3.2_4": { result: null, detail: "" },
    "3.2_5": { result: null, detail: "" },
    "3.2_6": { result: null, detail: "" },
    "3.2_7": { result: null, detail: "" },

    // 3.3 เฉพาะ sectionNumber === 3
    hv33: {
      result: null,
      detail: "",
      type: [],       // ["dropout", "switch", "rmu"]
      switchType: "", // ถ้าเลือก switch
    },

    // อื่นๆ
    other: "",
  },

  // Transformers array
  transformers: [
    {
      transformerData: {
        general: {
          testResult: "",
          capacity: "",
          hvVoltage: "",
          lvVoltage: "",
          impedance: "",
          vectorGroup: "",
          transformerType: "",
          transformerTypeOther: "",
          shortCircuitCurrent: "",
          correct: { result: null, detail: "" }
        },
        type: [],
        typeOther: "",
        correct: { result: null, detail: "" },
        overcurrent: { result: null, detail: "" },
        overcurrentType: [],
        overcurrentTypeOther: "",
        overcurrentAmp: "",
        overcurrentIc: "",
        surge: { result: null, detail: "" },
        surgeKV: "",
        surgeKA: "",
        ground: { result: null, detail: "" },
        groundOhm: "",
        groundCheck: { result: null, detail: "" },
        ext: {
          silica: { result: null, detail: "" },
          bushing: { result: null, detail: "" },
          oilLevel: { result: null, detail: "" },
          leak: { result: null, detail: "" }
        },
        sign: { result: null, detail: "" },
        other: ""
      },

      // LV System
      lvSystem: {
        standard: "",
        standardCorrect: null,
        standardNote: "",
        conductorType: "",
        otherConductorType: "",
        phaseWireSize: "",
        phaseWireSizeCorrect: null,
        phaseWireSizeNote: "",
        neutralWireSize: "",
        neutralWireSizeCorrect: null,
        neutralWireSizeNote: "",
        phaseIdentificationCorrect: null,
        phaseIdentificationNote: "",
        cablePathwayCorrect: null,
        cablePathwayNote: "",
        wiringMethod: "",
        cableTraySize: { width: "", height: "" },
        conduitSize: "",
        conduitSizeWall: "",
        otherWiringMethod: "",
        wiringMethodCorrect: null,
        wiringMethodNote: "",
        conduitType: "",
        otherConduitType: "",
        conduitTypeCorrect: null,
        conduitTypeNote: "",
        mainBreakerStandardCorrect: null,
        mainBreakerStandardNote: "",
        mainBreakerSize: "",
        mainBreakerSizeCorrect: null,
        mainBreakerSizeNote: "",
        shortCircuitRating: "",
        shortCircuitRatingCorrect: null,
        shortCircuitRatingNote: "",
        groundFaultProtectionCorrect: null,
        groundFaultProtectionNote: "",
        groundWireSize: "",
        groundWireSizeCorrect: null,
        groundWireSizeNote: "",
        groundingSystem: "",
        groundingSystemCorrect: null,
        groundingSystemNote: "",
        groundingConfig: "",
        tncsLoadBalance: false,
        tncsNeutralProtection: false,
        tncsTouchVoltageProtection: false,
        tncsCorrect: null,
        tncsNote: "",
        ttCorrect: null,
        ttNote: "",
        ttPartialCorrect: null,
        ttPartialNote: "",
        tnsCorrect: null,
        tnsNote: ""
      },

      // Panel Board (optional)
      panel: {
        hasPanelBoard: false,
        standard: [],
        standardCheck: { result: "", detail: "" },
        wireType: [],
        wireTypeOther: "",
        wireTypeCheck: { result: "", detail: "" },
        phaseSize: "",
        phaseSizeCheck: { result: "", detail: "" },
        neutralSize: "",
        neutralSizeCheck: { result: "", detail: "" },
        groundSize: "",
        groundSizeCheck: { result: "", detail: "" },
        phaseColor: { result: "", detail: "" },
        wirewayMechanical: { result: "", detail: "" },
        method: [],
        methodWirewayW: "",
        methodWirewayH: "",
        methodCableTrayW: "",
        methodCableTrayH: "",
        methodBuswayW: "",
        methodBuswayH: "",
        methodConduitWallSize: "",
        methodConduitBuriedSize: "",
        methodOther: "",
        methodCheck: { result: "", detail: "" },
        conduitType: [],
        conduitTypeOther: "",
        conduitCheck: { result: "", detail: "" },
        breakerStandard: { result: "", detail: "" },
        breakerSize: "",
        breakerCheck: { result: "", detail: "" },
        panelCapacity: { result: "", detail: "" },
        panelNeutralGround: { result: "", detail: "" }
      },

      // Sub Circuits
      subCircuits: [
        {
          circuitNo: "",
          evOnly: { result: null, detail: "" },
          evOnePerCircuit: { result: null, detail: "" },
          standard: [],
          wireType: [],
          wireTypeOther: "",
          phaseSize: "",
          phaseSizeCheck: { result: null, detail: "" },
          neutralSize: "",
          neutralSizeCheck: { result: null, detail: "" },
          groundSize: "",
          groundSizeCheck: { result: null, detail: "" },
          phaseColor: { result: null, detail: "" },
          wirewayMechanical: { result: null, detail: "" },
          method: [],
          methodConduitWallSize: "",
          methodConduitBuriedSize: "",
          methodWirewayW: "",
          methodWirewayH: "",
          methodCableTrayW: "",
          methodCableTrayH: "",
          methodOther: "",
          methodCheck: { result: null, detail: "" },
          conduitType: [],
          conduitTypeOther: "",
          conduitCheck: { result: null, detail: "" },
          breakerStandard: false,
          breakerMode3: false,
          breakerMode3AT: "",
          breakerMode2: false,
          breakerMode2AT: "",
          breakerCheck: { result: null, detail: "" },
          breakerSizeCheck: { result: null, detail: "" },
          rcdTypeB: false,
          rcdTypeBIn: "",
          rcdTypeAFPlusDD: false,
          rcdTypeBInCharger: false,
          rcdTypeBInChargerIn: "",
          rcdCheck: { result: null, detail: "" },
          rcdTypeBMain: { result: null, detail: "" },
          evChargers: [
            {
              product: "",
              model: "",
              sn: "",
              ip: "",
              chargeType: [],
              chargingHeads: "",
              totalPower: "",
              totalCurrent: "",
              mode: [],
              infoCheck: { result: null, detail: "" },
              headTypes: [],
              acType2Current: "",
              acType2Voltage: "",
              acType2Power: "",
              dcChadeMoCurrent: "",
              dcChadeMoVoltage: "",
              dcChadeMoPower: "",
              dcCcsCurrent: "",
              dcCcsVoltage: "",
              dcCcsPower: "",
              otherHeadType: "",
              otherCurrent: "",
              otherVoltage: "",
              otherPower: "",
              simultaneousCharge: "",
              simultaneousChargeDetail: "",
              headCheck: { result: null, detail: "" },
              mode2OutletGrounding: { result: null, detail: "" },
              mode2OutletFixed: { result: null, detail: "" },
              mode2WarningSign: { result: null, detail: "" },
              mode34DangerSign: { result: null, detail: "" },
              mode34EmergencySwitch: { result: null, detail: "" },
              mode34Ventilation: { result: null, detail: "" },
              mode34CableLength: { result: null, detail: "" },
              gasStationMode: { result: null, detail: "" },
              gasStationFixedCable: { result: null, detail: "" },
              gasStationMainSwitch: { result: null, detail: "" },
              gasStationSwitchDistance: { result: null, detail: "" },
              gasStationElectricalStandard: { result: null, detail: "" },
              gasStationSafetyDistance: { result: null, detail: "" },
              collisionProtection: "",
              fireProtection: "",
              lightningProtection: ""
            }
          ]
        }
      ]
    }
  ],

  summaryType: {
    overallResult: null,
  },

  limitation: "",

  signature: {
    officerSign: "",
    customerSign: "",
  }
};

// Helper functions
export const getNewSubCircuit = () => ({
  circuitNo: "",
  evOnly: { result: null, detail: "" },
  evOnePerCircuit: { result: null, detail: "" },
  standard: [],
  wireType: [],
  wireTypeOther: "",
  phaseSize: "",
  phaseSizeCheck: { result: null, detail: "" },
  neutralSize: "",
  neutralSizeCheck: { result: null, detail: "" },
  groundSize: "",
  groundSizeCheck: { result: null, detail: "" },
  phaseColor: { result: null, detail: "" },
  wirewayMechanical: { result: null, detail: "" },
  method: [],
  methodConduitWallSize: "",
  methodConduitBuriedSize: "",
  methodWirewayW: "",
  methodWirewayH: "",
  methodCableTrayW: "",
  methodCableTrayH: "",
  methodOther: "",
  methodCheck: { result: null, detail: "" },
  conduitType: [],
  conduitTypeOther: "",
  conduitCheck: { result: null, detail: "" },
  breakerStandard: false,
  breakerMode3: false,
  breakerMode3AT: "",
  breakerMode2: false,
  breakerMode2AT: "",
  breakerCheck: { result: null, detail: "" },
  breakerSizeCheck: { result: null, detail: "" },
  rcdTypeB: false,
  rcdTypeBIn: "",
  rcdTypeAFPlusDD: false,
  rcdTypeBInCharger: false,
  rcdTypeBInChargerIn: "",
  rcdCheck: { result: null, detail: "" },
  rcdTypeBMain: { result: null, detail: "" },
  evChargers: []
});

export const getNewEvCharger = () => ({
  product: "",
  model: "",
  sn: "",
  ip: "",
  chargeType: [],
  chargingHeads: "",
  totalPower: "",
  totalCurrent: "",
  mode: [],
  infoCheck: { result: null, detail: "" },
  headTypes: [],
  acType2Current: "",
  acType2Voltage: "",
  acType2Power: "",
  dcChadeMoCurrent: "",
  dcChadeMoVoltage: "",
  dcChadeMoPower: "",
  dcCcsCurrent: "",
  dcCcsVoltage: "",
  dcCcsPower: "",
  otherHeadType: "",
  otherCurrent: "",
  otherVoltage: "",
  otherPower: "",
  simultaneousCharge: "",
  simultaneousChargeDetail: "",
  headCheck: { result: null, detail: "" },
  mode2OutletGrounding: { result: null, detail: "" },
  mode2OutletFixed: { result: null, detail: "" },
  mode2WarningSign: { result: null, detail: "" },
  mode34DangerSign: { result: null, detail: "" },
  mode34EmergencySwitch: { result: null, detail: "" },
  mode34Ventilation: { result: null, detail: "" },
  mode34CableLength: { result: null, detail: "" },
  gasStationMode: { result: null, detail: "" },
  gasStationFixedCable: { result: null, detail: "" },
  gasStationMainSwitch: { result: null, detail: "" },
  gasStationSwitchDistance: { result: null, detail: "" },
  gasStationElectricalStandard: { result: null, detail: "" },
  gasStationSafetyDistance: { result: null, detail: "" },
  collisionProtection: "",
  fireProtection: "",
  lightningProtection: ""
});

export const getNewTransformer = () => ({
  transformerData: {
    general: {
      testResult: "",
      capacity: "",
      hvVoltage: "",
      lvVoltage: "",
      impedance: "",
      vectorGroup: "",
      transformerType: "",
      transformerTypeOther: "",
      shortCircuitCurrent: "",
      correct: { result: null, detail: "" }
    },
    type: [],
    typeOther: "",
    correct: { result: null, detail: "" },
    overcurrent: { result: null, detail: "" },
    overcurrentType: [],
    overcurrentTypeOther: "",
    overcurrentAmp: "",
    overcurrentIc: "",
    surge: { result: null, detail: "" },
    surgeKV: "",
    surgeKA: "",
    ground: { result: null, detail: "" },
    groundOhm: "",
    groundCheck: { result: null, detail: "" },
    ext: {
      silica: { result: null, detail: "" },
      bushing: { result: null, detail: "" },
      oilLevel: { result: null, detail: "" },
      leak: { result: null, detail: "" }
    },
    sign: { result: null, detail: "" },
    other: ""
  },
  lvSystem: {
    standard: "",
    standardCorrect: null,
    standardNote: "",
    conductorType: "",
    otherConductorType: "",
    phaseWireSize: "",
    phaseWireSizeCorrect: null,
    phaseWireSizeNote: "",
    neutralWireSize: "",
    neutralWireSizeCorrect: null,
    neutralWireSizeNote: "",
    phaseIdentificationCorrect: null,
    phaseIdentificationNote: "",
    cablePathwayCorrect: null,
    cablePathwayNote: "",
    wiringMethod: "",
    cableTraySize: { width: "", height: "" },
    conduitSize: "",
    conduitSizeWall: "",
    otherWiringMethod: "",
    wiringMethodCorrect: null,
    wiringMethodNote: "",
    conduitType: "",
    otherConduitType: "",
    conduitTypeCorrect: null,
    conduitTypeNote: "",
    mainBreakerStandardCorrect: null,
    mainBreakerStandardNote: "",
    mainBreakerSize: "",
    mainBreakerSizeCorrect: null,
    mainBreakerSizeNote: "",
    shortCircuitRating: "",
    shortCircuitRatingCorrect: null,
    shortCircuitRatingNote: "",
    groundFaultProtectionCorrect: null,
    groundFaultProtectionNote: "",
    groundWireSize: "",
    groundWireSizeCorrect: null,
    groundWireSizeNote: "",
    groundingSystem: "",
    groundingSystemCorrect: null,
    groundingSystemNote: "",
    groundingConfig: "",
    tncsLoadBalance: false,
    tncsNeutralProtection: false,
    tncsTouchVoltageProtection: false,
    tncsCorrect: null,
    tncsNote: "",
    ttCorrect: null,
    ttNote: "",
    ttPartialCorrect: null,
    ttPartialNote: "",
    tnsCorrect: null,
    tnsNote: ""
  },
  panel: {
    hasPanelBoard: false,
    standard: [],
    standardCheck: { result: "", detail: "" },
    wireType: [],
    wireTypeOther: "",
    wireTypeCheck: { result: "", detail: "" },
    phaseSize: "",
    phaseSizeCheck: { result: "", detail: "" },
    neutralSize: "",
    neutralSizeCheck: { result: "", detail: "" },
    groundSize: "",
    groundSizeCheck: { result: "", detail: "" },
    phaseColor: { result: "", detail: "" },
    wirewayMechanical: { result: "", detail: "" },
    method: [],
    methodWirewayW: "",
    methodWirewayH: "",
    methodCableTrayW: "",
    methodCableTrayH: "",
    methodBuswayW: "",
    methodBuswayH: "",
    methodConduitWallSize: "",
    methodConduitBuriedSize: "",
    methodOther: "",
    methodCheck: { result: "", detail: "" },
    conduitType: [],
    conduitTypeOther: "",
    conduitCheck: { result: "", detail: "" },
    breakerStandard: { result: "", detail: "" },
    breakerSize: "",
    breakerCheck: { result: "", detail: "" },
    panelCapacity: { result: "", detail: "" },
    panelNeutralGround: { result: "", detail: "" }
  },
  subCircuits: [getNewSubCircuit()]
});

export default initialEvHvChargerForm;