const evLvChargerFormSchema = {
  // General Information (ตรงกับ GeneralInfoLvSection)
  general: {
    powerAuthority: "",      // การไฟฟ้า
    inspectionNo: "",        // การตรวจสอบครั้งที่
    inspectionDate: "",      // วันที่ตรวจสอบ
    requestNo: "",           // การตรวจสอบตามคำร้องขอใช้ไฟเลขที่
    requestDate: "",         // วันที่คำร้อง
    userType: "individual",  // "individual" หรือ "corp"
    customerName: "",        // ชื่อ-นามสกุล (บุคคลธรรมดา)
    phone: "",               // โทรศัพท์ (บุคคลธรรมดา)
    corpName: "",            // ชื่อนิติบุคคล (นิติบุคคล)
    corpPhone: "",           // โทรศัพท์ (นิติบุคคล)
    address: "",             // ที่อยู่
    systemType: "",          // "3 เฟส (400 / 230 โวลต์)" หรือ "1 เฟส (230 โวลต์)"
    load: "",                // กระแสโหลด (A)
    evChargerCount: "",      // จำนวนเครื่องอัดประจุ
    evChargerPower: ""       // พิกัดกำลังไฟฟ้ารวม (kW)
  },

  // Documents
  documents: {
    electricalDocument: null // "has" or "none"
  },

  // LV System (PEA)
  LVSystemPEA: {
    standard: "",
    standardCorrect: null,
    standardNote: "",
    conductorType: "",
    otherConductorType: "",
    phaseWireSize: "",
    phaseWireSizeCorrect: null,
    phaseWireSizeNote: "",
    neutralWireSize: "",
    neutralWireSizeCorrect: null,
    neutralWireSizeNote: "",
    phaseIdentificationCorrect: null,
    phaseIdentificationNote: "",
    cablePathwayCorrect: null,
    cablePathwayNote: "",
    wiringMethod: "",
    cableTraySize: { width: "", height: "" },
    conduitSize: "",
    conduitSizeWall: "",
    otherWiringMethod: "",
    wiringMethodCorrect: null,
    wiringMethodNote: "",
    conduitType: "",
    otherConduitType: "",
    conduitTypeCorrect: null,
    conduitTypeNote: "",
    mainBreakerStandardCorrect: null,
    mainBreakerStandardNote: "",
    mainBreakerSize: "",
    mainBreakerSizeCorrect: null,
    mainBreakerSizeNote: "",
    shortCircuitRating: "",
    shortCircuitRatingCorrect: null,
    shortCircuitRatingNote: "",
    groundWireSize: "",
    groundWireSizeCorrect: null,
    groundWireSizeNote: "",
    groundingSystem: "",
    groundingSystemCorrect: null,
    groundingSystemNote: "",
    groundingConfig: "",
    tncsLoadBalance: false,
    tncsNeutralProtection: false,
    tncsTouchVoltageProtection: false,
    tncsCorrect: null,
    tncsNote: "",
    ttCorrect: null,
    ttNote: "",
    ttPartialCorrect: null,
    ttPartialNote: "",
  },

  // Panel Board (optional)
  panel: {
    hasPanelBoard: false,
    standard: [],
    standardCheck: { result: "", detail: "" },
    wireType: [],
    wireTypeOther: "",
    wireTypeCheck: { result: "", detail: "" },
    phaseSize: "",
    phaseSizeCheck: { result: "", detail: "" },
    neutralSize: "",
    neutralSizeCheck: { result: "", detail: "" },
    groundSize: "",
    groundSizeCheck: { result: "", detail: "" },
    phaseColor: { result: "", detail: "" },
    wirewayMechanical: { result: "", detail: "" },
    method: [],
    methodWirewayW: "",
    methodWirewayH: "",
    methodCableTrayW: "",
    methodCableTrayH: "",
    methodBuswayW: "",
    methodBuswayH: "",
    methodConduitWallSize: "",
    methodConduitBuriedSize: "",
    methodOther: "",
    methodCheck: { result: "", detail: "" },
    conduitType: [],
    conduitTypeOther: "",
    conduitCheck: { result: "", detail: "" },
    breakerStandard: { result: "", detail: "" },
    breakerSize: "",
    breakerCheck: { result: "", detail: "" },
    panelCapacity: { result: "", detail: "" },
    panelNeutralGround: { result: "", detail: "" },
  },

  // Sub Circuits
  subCircuits: [
    {
      circuitNo: "",
      evOnly: { result: null, detail: "" },
      evOnePerCircuit: { result: null, detail: "" },
      standard: [],
      wireType: [],
      wireTypeOther: "",
      phaseSize: "",
      phaseSizeCheck: { result: null, detail: "" },
      neutralSize: "",
      neutralSizeCheck: { result: null, detail: "" },
      groundSize: "",
      groundSizeCheck: { result: null, detail: "" },
      phaseColor: { result: null, detail: "" },
      wirewayMechanical: { result: null, detail: "" },
      method: [],
      methodConduitWallSize: "",
      methodConduitBuriedSize: "",
      methodWirewayW: "",
      methodWirewayH: "",
      methodCableTrayW: "",
      methodCableTrayH: "",
      methodOther: "",
      methodCheck: { result: null, detail: "" },
      conduitType: [],
      conduitTypeOther: "",
      conduitCheck: { result: null, detail: "" },
      breakerStandard: false,
      breakerMode3: false,
      breakerMode3AT: "",
      breakerMode2: false,
      breakerMode2AT: "",
      breakerCheck: { result: null, detail: "" },
      breakerSizeCheck: { result: null, detail: "" },
      rcdTypeB: false,
      rcdTypeBIn: "",
      rcdTypeAFPlusDD: false,
      rcdTypeBInCharger: false,
      rcdTypeBInChargerIn: "",
      rcdCheck: { result: null, detail: "" },
      rcdTypeBMain: { result: null, detail: "" },
      evChargers: [
        {
          product: "",
          model: "",
          sn: "",
          ip: "",
          chargeType: [],
          chargingHeads: "",
          totalPower: "",
          totalCurrent: "",
          mode: [],
          infoCheck: { result: null, detail: "" },
          headTypes: [],
          acType2Current: "",
          acType2Voltage: "",
          acType2Power: "",
          dcChadeMoCurrent: "",
          dcChadeMoVoltage: "",
          dcChadeMoPower: "",
          dcCcsCurrent: "",
          dcCcsVoltage: "",
          dcCcsPower: "",
          otherHeadType: "",
          otherCurrent: "",
          otherVoltage: "",
          otherPower: "",
          simultaneousCharge: "",
          simultaneousChargeDetail: "",
          headCheck: { result: null, detail: "" },
          mode2OutletGrounding: { result: null, detail: "" },
          mode2OutletFixed: { result: null, detail: "" },
          mode2WarningSign: { result: null, detail: "" },
          mode34DangerSign: { result: null, detail: "" },
          mode34EmergencySwitch: { result: null, detail: "" },
          mode34Ventilation: { result: null, detail: "" },
          mode34CableLength: { result: null, detail: "" },
          gasStationMode: { result: null, detail: "" },
          gasStationFixedCable: { result: null, detail: "" },
          gasStationMainSwitch: { result: null, detail: "" },
          gasStationSwitchDistance: { result: null, detail: "" },
          gasStationElectricalStandard: { result: null, detail: "" },
          gasStationSafetyDistance: { result: null, detail: "" },
          collisionProtection: "",
          fireProtection: "",
          lightningProtection: ""
        }
      ]
    }
  ],

  summaryType: {
    overallResult: null,
  },

  limitation: "",

  signature: {
    officerSign: "",
    customerSign: "",
  }
};

// Helper functions
export const getNewLvSubCircuit = () => ({
  circuitNo: "",
  evOnly: { result: null, detail: "" },
  evOnePerCircuit: { result: null, detail: "" },
  standard: [],
  wireType: [],
  wireTypeOther: "",
  phaseSize: "",
  phaseSizeCheck: { result: null, detail: "" },
  neutralSize: "",
  neutralSizeCheck: { result: null, detail: "" },
  groundSize: "",
  groundSizeCheck: { result: null, detail: "" },
  phaseColor: { result: null, detail: "" },
  wirewayMechanical: { result: null, detail: "" },
  method: [],
  methodConduitWallSize: "",
  methodConduitBuriedSize: "",
  methodWirewayW: "",
  methodWirewayH: "",
  methodCableTrayW: "",
  methodCableTrayH: "",
  methodOther: "",
  methodCheck: { result: null, detail: "" },
  conduitType: [],
  conduitTypeOther: "",
  conduitCheck: { result: null, detail: "" },
  breakerStandard: false,
  breakerMode3: false,
  breakerMode3AT: "",
  breakerMode2: false,
  breakerMode2AT: "",
  breakerCheck: { result: null, detail: "" },
  breakerSizeCheck: { result: null, detail: "" },
  rcdTypeB: false,
  rcdTypeBIn: "",
  rcdTypeAFPlusDD: false,
  rcdTypeBInCharger: false,
  rcdTypeBInChargerIn: "",
  rcdCheck: { result: null, detail: "" },
  rcdTypeBMain: { result: null, detail: "" },
  evChargers: []
});

export const getNewLvEvCharger = () => ({
  product: "",
  model: "",
  sn: "",
  ip: "",
  chargeType: [],
  chargingHeads: "",
  totalPower: "",
  totalCurrent: "",
  mode: [],
  infoCheck: { result: null, detail: "" },
  headTypes: [],
  acType2Current: "",
  acType2Voltage: "",
  acType2Power: "",
  dcChadeMoCurrent: "",
  dcChadeMoVoltage: "",
  dcChadeMoPower: "",
  dcCcsCurrent: "",
  dcCcsVoltage: "",
  dcCcsPower: "",
  otherHeadType: "",
  otherCurrent: "",
  otherVoltage: "",
  otherPower: "",
  simultaneousCharge: "",
  simultaneousChargeDetail: "",
  headCheck: { result: null, detail: "" },
  mode2OutletGrounding: { result: null, detail: "" },
  mode2OutletFixed: { result: null, detail: "" },
  mode2WarningSign: { result: null, detail: "" },
  mode34DangerSign: { result: null, detail: "" },
  mode34EmergencySwitch: { result: null, detail: "" },
  mode34Ventilation: { result: null, detail: "" },
  mode34CableLength: { result: null, detail: "" },
  gasStationMode: { result: null, detail: "" },
  gasStationFixedCable: { result: null, detail: "" },
  gasStationMainSwitch: { result: null, detail: "" },
  gasStationSwitchDistance: { result: null, detail: "" },
  gasStationElectricalStandard: { result: null, detail: "" },
  gasStationSafetyDistance: { result: null, detail: "" },
  collisionProtection: "",
  fireProtection: "",
  lightningProtection: ""
});

export default evLvChargerFormSchema;